version: '3.8'

services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OTEL_SERVICE_NAME=fast-demo
      - OTEL_TRACES_EXPORTER=otlp 
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_TRACES_INSECURE=true
      - OTEL_EXPORTER_OTLP_METRICS_INSECURE=true
    

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - /home/buteco/estudos/demo/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # GRPC
      - "4318:4318" # HTTP
      - "8888:8888" # Metrics OpenTelemetry